### ISSUE TITLE
Add a function to reset a key in the array buffer

### ISSUE THREAD

**Issue by metaa** [WootingKb/wooting-rgb-sdk#11]
Currently you can only reset single keys with `wooting_rgb_direct_reset_key` or the whole keyboard with `wooting_rgb_reset`.

It would be nice to have an array function here, analog to the painting functions.

**Comment by GottZ** [comment]
so you want to send a mask of keys you want to reset to it? like a full array of rgb but in this case with plain bits for each key?

**Comment by metaa** [comment]
I would expect it to pretty much work like `wooting_rgb_array_set_single` so that I could then render the changes to the keyboard with `wooting_rgb_array_update_keyboard`.

**Comment by PastaJ36** [comment]
Good suggestion. I think having it as a mask API would be clean, so it could support all use cases. I'm not sure if we can make it in a way that it is as fast as just resetting one key though.
