### ISSUE TITLE
Please attach dll files in releases as assets

### ISSUE THREAD

**Issue by metaa** [WootingKb/wooting-rgb-sdk#12]
I'm attempting to automate a process that downloads the latest `dll` files from this repository.

Currently, the release posts just link to the files manually instead of them being added as an asset which makes it a bit harder to find them programmatically.

Although I could work around this, it would be really nice to get this in order.
![Gif](https://help.github.com/assets/images/help/releases/releases_adding_binary.gif)

Please consider fixing this 🌝

**Comment by GottZ** [comment]
ye. this repo should be added to a ci solution to automagically build on commit

**Comment by PastaJ36** [comment]
CI solution is indeed the goal. Will add that to the SDK improvements list. We'll be getting on it in about 2 weeks. I'll add them manually until we do.

**Comment by metaa** [comment]
Awesome, thanks!
