### ISSUE TITLE
Implement something like an SDK "ping"?

### ISSUE THREAD

**Issue by metaa** [WootingKb/wooting-rgb-sdk#14]
As I was sitting here looking at my Wooting keyboard, I realized that it's been stuck with an RGB pattern that a script of mine drew on it.

The problem is, I **killed** the script a while ago, so its shutdown handler never called the reset function and never reset the LEDs which also renders the A1, A2, A3 and Mode keys useless until I unplug the keyboard or reset it using another script that utilizes the SDK.

What I'm trying to suggest to resolve that is quite simple:

Maybe introduce something like a ping function to tell the keyboard that something is still actively using the SDK. Once there is a ping timeout (after like 1 minute?), automatically reset the keyboard.

**Comment by GottZ** [comment]
hm. command 1 is ping. i assume it could be added to the firmware easily.
