### ISSUE TITLE
support osx

### ISSUE THREAD

**Issue by jBernz** [WootingKb/wooting-rgb-sdk#18]
hi I'm using the wooting one as a midi controller, and would like the lights to interact with midi signals. Obviously there is some osx interface into the lights as wootility is able to modify them, but I don't see support for that here. Do you have plans to add the rgb sdk for osx? If not is there some way I can interact with it anyway?

**Comment by jBernz** [comment]
so I made a fork with an osx makefile just in case anybody wanted to run this from osx: https://github.com/jBernz/wooting-rgb-sdk

**Comment by PastaJ36** [comment]
Thanks for making it, I'll check it out on my Mac. Would be nice to have all platforms supported. Can you submit it as a PR?

**Comment by PastaJ36** [comment]
Many thanks @jBernz, works great. We're adding your fork to the SDK.
