### ISSUE TITLE
Keyboard can not be found on Linux

### ISSUE THREAD

**Issue by PastaJ36** [WootingKb/wooting-rgb-sdk#2]
We try to look for the keyboard by filtering for the Usage Page, but hidapi doesn't return them correctly. I remember reading somewhere that you can pick different USB drivers, but I don't have time to look into. Would appreciate if a linux user can investigate.

Edit: I'm assuming this is not a problem for OSX, but not sure yet

**Comment by vtkacenko** [comment]
@PastaJ36 works for me on Linux when run with elevated privileges - `sudo ./example-app`

**Comment by PastaJ36** [comment]
Alright nevermind, I'll add it to the docs later

**Comment by PastaJ36** [comment]
Changed to opening with interface number: e78ce0c0aae67f47cc053f7c1426db4c9afec36e
