### ISSUE TITLE
Wooting 2HE, LE and 60HE crashing on FW 2.5.9

### ISSUE THREAD

**Issue by BigBrainAFK** [WootingKb/wooting-rgb-sdk#48]
So I have updated my W2HE to 2.5.9 and ever since that it started to hang/crash when the RGB SDK interacts with it.
Sometimes I also got it to crash by changing RGB in the Wootility and some others had the same issue [here](https://discord.com/channels/167181566978555904/590898276182523955/990301945937932369)

I have then tried the same on the LE which lead to similar results.
The 60HE seems to crash when playing around with RGB on the Wootility.
Crashing occurs anywhere from 30seconds to 1minute from my latest "testing"

This doesnt happen when using FW 2.4.14

**Comment by simon-wh** [comment]
In what situation are you replicating this? I've got a test script which just continually cycles key colours and so far I haven't been able to replicate it

**Comment by simon-wh** [comment]
Which build of the rgb sdk were you using? Are you using the 60he support branch? At least, that should be the only way to even run it on 60HE. So far I haven't been able to replicate it on my 60HE.

I'm asking, as my current theory as to why it occurs would only make sense if it occurs only on Two HE

**Comment by BigBrainAFK** [comment]
RE: 60HE seems to not crash anymore. I does pause when quickly switching RGB effects but not actually crash

**Comment by BigBrainAFK** [comment]
Seems to be fixed as of FW 2.5.10 on all Keyboards mentioned.
