### ISSUE TITLE
USAGE_PAGE out of spec

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wooting-rgb-sdk#5]
The value of the define "WOOTING_ONE_CONFIG_USAGE_PAGE" are not in the valid range of FF00 - FFFF.

https://github.com/WootingKb/wooting-rgb-sdk/blob/746670ea43779d439a940a2ce46d6050cfaa2929/src/wooting-usb.c#L10

**Comment by PastaJ36** [comment]
Changed to opening with interface number: e78ce0c0aae67f47cc053f7c1426db4c9afec36e
